//
// shader.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif

#ifndef __ISPC_STRUCT_Vec4__
#define __ISPC_STRUCT_Vec4__
struct Vec4 {
    float x;
    float y;
    float z;
    float w;
};
#endif

#ifndef __ISPC_STRUCT_Vec2__
#define __ISPC_STRUCT_Vec2__
struct Vec2 {
    float x;
    float y;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void CubeStartColorShader(const float col[][4], struct Vec4 * BarCord, struct Vec4 * r);
    extern float E(struct Vec2 * V, struct Vec2 * VP);
    extern void ambientLightShader(const struct Vec4 * ObjColor, const struct Vec4 * LightSourceColor, struct Vec4 * Color);
    extern void colorBarShader(const float col[][4], struct Vec4 * BarCord, struct Vec4 * r);
    extern void colorCubeLightSourceShader(const float col[][4], struct Vec4 * BarCord, struct Vec4 * r);
    extern void colorShader(const float col[][4], struct Vec4 * BarCord, struct Vec4 * r);
    extern void diffusalLightShader(const struct Vec4 * ObjColor, const struct Vec4 * LightColor, const struct Vec4 * LightDir, const struct Vec4 * Norm, struct Vec4 * r);
    extern float getX(struct Vec2 * obj);
    extern float getY(struct Vec2 * obj);
    extern void textureShader(const uint32_t * data, const uint32_t * width, const uint32_t * height, const float uv[][2], const struct Vec4 * BarCord, uint32_t * color);
    extern void vertexShader(const float * rotatedWorldViewProj, const float * vpos4f_i, struct Vec4 * r);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
